okta:
  oauth2:
    issuer: https://dev-5um7h52037bdwgaf.eu.auth0.com/
    client-id: dNuKA5MOv8BeOnrWZzE99SNOvasjEXMz
    client-secret: _kc2rA7Di2a_j3ZkCwYqHsapZuRKn16r3XvAEyGK6ohnaypEZpT5Zt2Tzy3BTHD5
    bearer-token: ${BEARER_TOKEN}

server:
  port: 8081

spring:
  application:
    name: ristorante

  # Configurazione database
  datasource:
    url: jdbc:mysql://${DATABASE_MYSQL_HOSTNAME}:${DATABASE_MYSQL_PORT}/${DATABASE_MYSQL_NAME}?ssl-mode=REQUIRED
    username: ${DATABASE_MYSQL_USERNAME}
    password: ${DATABASE_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.mariadb.jdbc.Driver
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

  data:
    jpa:
      repositories:
        # DEFAULT: i repositories vengono controllati all'avvio dell'applicazione
        # DEFERRED: i repositories vengono controllati all'avvio dell'applicazione ma in maniera asincrona
        # LAZY: i repositories vengono controllati solo quando sono richiamati
        bootstrap-mode: DEFAULT

  # JPA
  jpa:
    hibernate:
      # Values:
        # none : non viene apportata alcuna modifica al database. Valore DA METTERE in produzione
        # update: crea le tabelle ed i relativi campi sul database qualora lì non esistano.
                  # Altresi modifica le tabelle esistenti aggiungendo solo i campi nuovi ma non modificando quelli preesistenti.
        # create-drop: crea le tabelle all'avvio dell'applicazione e ne fa il drop quando stoppo l'applicazione
        # validated: confronta le classi (entita) con le tabelle; se trova discrepanze solleva una eccezione.
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      #dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    open-in-view: false


logging:
  level:
    '[it.fabio.ristorante]': info
    '[org.hibernate.orm.jdbc.bind]': trace
    '[org.springframework.boot]': info

spring-doc:
  swagger-ui:
    enabled: true
    # hostname:port/swagger-ui.html => localhost:8081/swagger-ui.html
    path: /swagger-ui.html







